version: '3.8'

networks:
  gitlab_review_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

services:
  ollama:
    container_name: fn_ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      gitlab_review_network:
        ipv4_address: 172.21.0.10
    restart: unless-stopped

  gitlab-review:
    container_name: fn_gitlab_review
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9655:80"
    environment:
      - AI_SERVICE_TYPE=${AI_SERVICE_TYPE:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL:-gpt-3.5-turbo}
      - AZURE_OPENAI_API_BASE=${AZURE_OPENAI_API_BASE}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-custom-qwen}
      - OLLAMA_TIMEOUT=${OLLAMA_TIMEOUT:-120}
      - OLLAMA_MAX_TOKENS=${OLLAMA_MAX_TOKENS:-1800}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_URL=${GITLAB_URL}
      - EXPECTED_GITLAB_TOKEN=${EXPECTED_GITLAB_TOKEN}
    networks:
      gitlab_review_network:
        ipv4_address: 172.21.0.11
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama-data:
