FROM python:3.9-slim-buster

WORKDIR /app

COPY docker/gitlab-review/requirements.txt /app/
COPY docker/gitlab-review/main.py /app/
COPY docker/gitlab-review/*.py /app/

RUN pip install -r requirements.txt gunicorn

EXPOSE 80

CMD ["gunicorn", "--bind", "0.0.0.0:80", "main:app"]
